#!/bin/sh
# TeamLynx squad router setup - generated by `lynx-field netconfig`; re-generate, do not edit.
# Squad LYNX: SSID LYNX-SQUAD, 10 nodes, LAN 192.168.8.0/24.
# Run on the router (OpenWrt 21.02+ or GL.iNet 4.x):  sh lynx-router-setup.sh
set -eu

# --- system: hostname; time follows the squad leader (the router has no RTC) -----------
uci set system.@system[0].hostname='lynx-router'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='1'
uci -q delete system.ntp.server || true
uci add_list system.ntp.server='192.168.8.11'

# --- LAN -------------------------------------------------------------------------------
uci set network.lan.ipaddr='192.168.8.1'
uci set network.lan.netmask='255.255.255.0'

# --- radio: keep the hardware section, set channel/regdomain/rates ----------------------
RADIO=''
OTHERS=''
for r in $(uci -q show wireless | sed -n 's/^wireless\.\([^.=]*\)=wifi-device$/\1/p'); do
  band=$(uci -q get wireless.$r.band || true)
  hw=$(uci -q get wireless.$r.hwmode || true)
  if [ -z "$RADIO" ] && { [ "$band" = '2g' ] || [ "$hw" = '11g' ]; }; then
    RADIO=$r
  else
    OTHERS="$OTHERS $r"
  fi
done
[ -n "$RADIO" ] || { echo 'no 2g radio found' >&2; exit 1; }
uci set wireless.$RADIO.disabled='0'
uci set wireless.$RADIO.channel='6'
uci set wireless.$RADIO.htmode='HT20'
uci set wireless.$RADIO.country='GB'
uci set wireless.$RADIO.legacy_rates='0'
uci set wireless.$RADIO.cell_density='1'
for r in $OTHERS; do uci set wireless.$r.disabled='1'; done

# --- one offline AP: WPA3-SAE, PMF required, WMM on, no low-ACK kick -----------------
while uci -q delete wireless.@wifi-iface[0]; do :; done
uci set wireless.lynx=wifi-iface
uci set wireless.lynx.device="$RADIO"
uci set wireless.lynx.network='lan'
uci set wireless.lynx.mode='ap'
uci set wireless.lynx.ssid='LYNX-SQUAD'
uci set wireless.lynx.encryption='sae'
uci set wireless.lynx.key='change-this-squad-passphrase'
uci set wireless.lynx.ieee80211w='2'
uci set wireless.lynx.wmm='1'
uci set wireless.lynx.isolate='0'
uci set wireless.lynx.disassoc_low_ack='0'
uci set wireless.lynx.dtim_period='1'
uci set wireless.lynx.max_inactivity='30'

# --- DHCP: static lease per node, DNS names for the relays --------------------------
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='50'
uci set dhcp.lan.leasetime='12h'
uci set dhcp.@dnsmasq[0].domain='lynx'
uci set dhcp.@dnsmasq[0].local='/lynx/'
uci -q delete dhcp.@dnsmasq[0].address || true
uci add_list dhcp.@dnsmasq[0].address='/relay.lynx/192.168.8.1'
uci add_list dhcp.@dnsmasq[0].address='/relay2.lynx/192.168.8.11'
while uci -q delete dhcp.@host[0]; do :; done
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n01'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:01'
uci set dhcp.@host[-1].ip='192.168.8.11'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n02'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:02'
uci set dhcp.@host[-1].ip='192.168.8.12'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n03'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:03'
uci set dhcp.@host[-1].ip='192.168.8.13'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n04'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:04'
uci set dhcp.@host[-1].ip='192.168.8.14'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n05'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:05'
uci set dhcp.@host[-1].ip='192.168.8.15'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n06'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:06'
uci set dhcp.@host[-1].ip='192.168.8.16'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n07'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:07'
uci set dhcp.@host[-1].ip='192.168.8.17'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n08'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:08'
uci set dhcp.@host[-1].ip='192.168.8.18'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n09'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:09'
uci set dhcp.@host[-1].ip='192.168.8.19'
uci set dhcp.@host[-1].dns='1'
uci add dhcp host >/dev/null
uci set dhcp.@host[-1].name='lynx-n10'
uci set dhcp.@host[-1].mac='48:b0:2d:00:00:0a'
uci set dhcp.@host[-1].ip='192.168.8.20'
uci set dhcp.@host[-1].dns='1'

# --- firewall: relay, beacon, mDNS from the LAN ---------------------------------------
uci -q delete firewall.lynx_relay || true
uci set firewall.lynx_relay=rule
uci set firewall.lynx_relay.name='lynx-relay'
uci set firewall.lynx_relay.src='lan'
uci set firewall.lynx_relay.proto='tcp'
uci set firewall.lynx_relay.dest_port='8765'
uci set firewall.lynx_relay.target='ACCEPT'
uci -q delete firewall.lynx_beacon || true
uci set firewall.lynx_beacon=rule
uci set firewall.lynx_beacon.name='lynx-beacon'
uci set firewall.lynx_beacon.src='lan'
uci set firewall.lynx_beacon.proto='udp'
uci set firewall.lynx_beacon.dest_port='8766'
uci set firewall.lynx_beacon.target='ACCEPT'
uci -q delete firewall.lynx_mdns || true
uci set firewall.lynx_mdns=rule
uci set firewall.lynx_mdns.name='lynx-mdns'
uci set firewall.lynx_mdns.src='lan'
uci set firewall.lynx_mdns.proto='udp'
uci set firewall.lynx_mdns.dest_port='5353'
uci set firewall.lynx_mdns.target='ACCEPT'

uci commit
# --- services ---------------------------------------------------------------------------
[ -x /etc/init.d/lynx-relay ] && /etc/init.d/lynx-relay enable || echo 'lynx-relay missing: install-relay.sh'
[ -x /etc/init.d/umdns ] && /etc/init.d/umdns enable || true
/etc/init.d/sysntpd restart || true
/etc/init.d/dnsmasq restart
/etc/init.d/firewall reload
/etc/init.d/network reload
wifi reload
[ -x /etc/init.d/lynx-relay ] && /etc/init.d/lynx-relay restart || true
echo 'TeamLynx router ready: SSID LYNX-SQUAD on '"$RADIO"', relay ws://192.168.8.1:8765'
