"""``lynx-field headset``: start one headset in the field from its node profile.

The profile (``/etc/lynx/node.json``, generated by ``lynx-field netconfig``) names the node,
sensors, site and directories. Start-up, with no operator input beyond the rail switch:

1. **Calibrate** if the profile asks for it (``calibrate``: ``always`` | ``if-missing`` |
   ``if-stale`` | ``never``; stale = older than ``calibrate_max_age_h``): the staging prompt runs on
   the helmet display and the operator taps the rail switch on each marker
   (:mod:`lynx.field.staging`).
2. **Resolve relays**: profile ``relay_urls`` first, then beacon / mDNS / DNS / gateway discovery
   (:func:`lynx.field.discovery.resolve_relay_urls`); the list is refreshed whenever a whole
   failover cycle fails.
3. **Pose source**: ``gnss:`` (IMU + GNSS) if the profile has a GNSS port and the site a datum,
   else ``serial:`` at the calibrated station position, with ``cal=<cal_dir>/imu.json``.
4. **Run** :class:`lynx.headset.app.HeadsetClient` on a :class:`~lynx.field.failover.FailoverClient`
   with :class:`FieldHook`: friendly holdover on link loss, drift / GNSS alerts, session log, and
   the systemd watchdog (``WATCHDOG=1`` once per second from the render loop, so a hung loop is
   restarted by ``lynx-headset.service``).

``--dry-run`` prints the resolved plan as JSON and exits.
"""

from __future__ import annotations

import json
import logging
import os
import socket
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from lynx.net.schema import Team

from .calibrate import DriftMonitor, FieldCalibration

log = logging.getLogger("lynx.launcher")

CALIBRATE_MODES = ("always", "if-missing", "if-stale", "never")


@dataclass
class NodeProfile:
    node: int
    callsign: str
    team: str = "blue"
    role: str = "operator"
    squad: str = "LYNX"
    relay_urls: List[str] = field(default_factory=list)
    discovery: bool = True
    imu: Optional[str] = "/dev/lynx-imu"
    gnss: Optional[str] = None
    site: Optional[str] = "/etc/lynx/site.json"
    cal_dir: str = "/var/lib/lynx"
    log_dir: Optional[str] = "/var/log/lynx"
    calibrate: str = "if-stale"
    calibrate_max_age_h: float = 12.0
    station: Optional[str] = None
    markers: List[str] = field(default_factory=list)
    camera: Dict[str, object] = field(default_factory=lambda: {"source": "0", "hfov": 78.0})
    telemetry_hz: float = 20.0
    imu_report: str = "rv"
    headset_args: List[str] = field(default_factory=list)
    relay_role: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "NodeProfile":
        unknown = set(d) - set(cls.__dataclass_fields__)
        if unknown:
            raise ValueError(f"unknown node profile fields {sorted(unknown)}")
        p = cls(**d)
        if not 1 <= int(p.node) <= 0xFFFF:
            raise ValueError("node must be 1..65535")
        if len(p.callsign) > 8 or not p.callsign.isascii():
            raise ValueError("callsign must be at most 8 ASCII characters")
        if p.team.upper() not in Team.__members__:
            raise ValueError(f"team must be one of {[t.name.lower() for t in Team]}")
        if p.calibrate not in CALIBRATE_MODES:
            raise ValueError(f"calibrate must be one of {CALIBRATE_MODES}")
        return p

    @classmethod
    def load(cls, path: str) -> "NodeProfile":
        return cls.from_dict(json.loads(Path(path).read_text()))


# ----------------------------------------------------------------------------------- planning


def load_calibration(profile: NodeProfile) -> Optional[FieldCalibration]:
    try:
        cal = FieldCalibration.load(profile.cal_dir)
    except (OSError, ValueError, KeyError):
        return None
    return cal if cal.node == profile.node else None


def needs_calibration(profile: NodeProfile, cal: Optional[FieldCalibration], now: Optional[float] = None) -> bool:
    mode = profile.calibrate
    if mode == "never" or not profile.imu or not profile.site:
        return False
    if mode == "always" or cal is None:
        return True
    if mode == "if-stale":
        age_h = ((time.time() if now is None else now) - cal.time_unix) / 3600.0
        return age_h > profile.calibrate_max_age_h
    return False


def pose_spec(profile: NodeProfile, cal: Optional[FieldCalibration], site_has_datum: bool) -> str:
    if not profile.imu:
        return "keyboard"
    opts = []
    imu_json = Path(profile.cal_dir) / "imu.json"
    if cal is not None and imu_json.exists():
        opts.append(f"cal={imu_json}")
    if profile.gnss and profile.site and site_has_datum:
        q = "&".join([f"gnss={profile.gnss}", f"site={profile.site}", *opts])
        return f"gnss:{profile.imu}?{q}"
    return f"serial:{profile.imu}" + (f"?{'&'.join(opts)}" if opts else "")


def headset_argv(profile: NodeProfile, cal: Optional[FieldCalibration], url: str, site_has_datum: bool) -> List[str]:
    cam = dict(profile.camera)
    argv = ["--url", url, "--node", str(profile.node), "--callsign", profile.callsign, "--team", profile.team,
            "--rate", str(profile.telemetry_hz), "--pose", pose_spec(profile, cal, site_has_datum),
            "--source", str(cam.get("source", "0")), "--hfov", str(cam.get("hfov", 78.0))]
    for key in ("width", "height"):
        if key in cam:
            argv += [f"--{key}", str(cam[key])]
    if cal is not None:
        x, y, z = cal.position
        argv += ["--x", f"{x:.3f}", "--y", f"{y:.3f}", "--eye-height", f"{z:.3f}"]
    return argv + list(profile.headset_args)


# ----------------------------------------------------------------------------------- hooks


def sd_notify(message: str) -> bool:
    """Send ``message`` to systemd's notify socket (no-op outside a ``Type=notify`` unit)."""
    addr = os.environ.get("NOTIFY_SOCKET")
    if not addr:
        return False
    if addr.startswith("@"):
        addr = "\0" + addr[1:]
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM) as s:
            s.connect(addr)
            s.sendall(message.encode())
        return True
    except OSError:
        return False


class FieldHook:
    """:class:`lynx.headset.app.HeadsetHook` combining the field behaviours for one headset."""

    def __init__(self, holdover=None, drift: Optional[DriftMonitor] = None, recorder=None, pose_source=None,
                 failover=None, watchdog_s: float = 1.0) -> None:
        self.holdover = holdover
        self.drift = drift
        self.recorder = recorder
        self.pose_source = pose_source
        self.failover = failover
        self.watchdog_s = watchdog_s
        self._ready = False
        self._last_dog = 0.0
        self._own_pings: set = set()
        self._drift_alert: Optional[str] = None
        self._drift_checked = 0.0
        if failover is not None and recorder is not None:
            failover.listeners.append(lambda ev: recorder.record_event(ev.kind, url=ev.url, detail=ev.detail))

    def teammates(self, teammates, nodes, now, connected):
        if self.holdover is not None:
            return self.holdover.update(teammates, now, connected)
        return teammates

    def annotate(self, client, pose, now, alerts, telemetry) -> None:
        if self.holdover is not None:
            self.holdover.annotate(client, pose, now, alerts, telemetry)
        fix = getattr(self.pose_source, "last_fix", None)
        if self.pose_source is not None and getattr(self.pose_source, "gnss_ok", True) is False:
            alerts.append("! GNSS NO FIX - POSITION HELD")
        if self.drift is not None:
            if fix is not None:
                self.drift.add_course_sample(time.time(), pose.yaw, pose.pitch, fix.course_deg, fix.speed_mps)
            if now - self._drift_checked >= 5.0:
                self._drift_checked = now
                est = self.drift.estimate(time.time())
                self._drift_alert = est.alert()
                telemetry["HDG"] = f"TARE {est.minutes_since_tare:.0f}MIN EST ERR {est.predicted_error_deg:.1f}DEG"
                if est.cog_bias_deg is not None:
                    telemetry["HDG"] += f" COG {est.cog_bias_deg:+.0f}"
            if self._drift_alert:
                alerts.append(self._drift_alert)
        if self.recorder is not None and client is not None:
            link = client.net.connected
            self.recorder.record_pose(client.config.node_id, client.config.callsign,
                                      Team(client.config.team).name.lower(), pose.x, pose.y, pose.z, pose.yaw,
                                      pose.pitch, pose.roll, link)
            for ps in client.client.own_pings():
                key = (ps.ping.owner, ps.ping.ping_id)
                if key not in self._own_pings:
                    self._own_pings.add(key)
                    self.recorder.record_message(ps.ping)
        if not self._ready:
            self._ready = sd_notify("READY=1")
        if now - self._last_dog >= self.watchdog_s:
            self._last_dog = now
            sd_notify("WATCHDOG=1")


# ----------------------------------------------------------------------------------- run


@dataclass
class LaunchPlan:
    profile: dict
    urls: List[str]
    calibrate: bool
    calibration: Optional[dict]
    argv: List[str]


def plan(profile: NodeProfile, urls: Optional[Sequence[str]] = None, now: Optional[float] = None) -> LaunchPlan:
    from .discovery import resolve_relay_urls
    from .site import Site

    cal = load_calibration(profile)
    has_datum = False
    if profile.site and Path(profile.site).exists():
        has_datum = Site.load(profile.site).datum is not None
    if urls is None:
        urls = resolve_relay_urls(profile.relay_urls, beacon=profile.discovery, squad=profile.squad,
                                  mdns=profile.discovery) or ["ws://relay.lynx:8765"]
    urls = list(urls)
    return LaunchPlan(asdict(profile), urls, needs_calibration(profile, cal, now),
                      cal.to_dict() if cal else None, headset_argv(profile, cal, urls[0], has_datum))


def run_calibration(profile: NodeProfile, display: bool = True) -> FieldCalibration:
    from lynx.hw import ImuCalibration, ImuLink

    from .gnss import GnssReader
    from .site import Site
    from .staging import PromptDisplay, StagingCalibrator, StagingOptions, save_calibration

    site = Site.load(profile.site)
    imu_json = Path(profile.cal_dir) / "imu.json"
    imu_cal = ImuCalibration.load(imu_json) if imu_json.exists() else ImuCalibration()
    imu_cal.heading_offset_deg, imu_cal.tared = 0.0, False
    imu_cal.declination_deg = site.declination_deg
    imu_cal.convergence_deg = site.convergence_deg
    markers = profile.markers or sorted(site.markers)[:1]
    link = ImuLink.open(profile.imu, imu_cal).start()
    gnss = None
    try:
        if profile.station is None and profile.gnss and site.datum is not None:
            gnss = GnssReader.open(profile.gnss).start()
        opts = StagingOptions(node=profile.node, markers=markers, station=profile.station)
        disp = PromptDisplay() if display else None
        try:
            cal = StagingCalibrator(site, link, opts, gnss=gnss, display=disp).run()
        finally:
            if disp is not None:
                disp.close()
        save_calibration(cal, profile.cal_dir)
        return cal
    finally:
        link.stop()
        if gnss is not None:
            gnss.stop()


def run_headset(profile: NodeProfile, urls: Optional[Sequence[str]] = None, headless: bool = False,
                frames: int = 0, extra_argv: Sequence[str] = ()) -> int:
    from lynx.headset.app import HeadsetClient, build_parser, config_from_args, run
    from lynx.headset.pose import PoseSourceUnavailableError, create_pose_source
    from lynx.headset.sources import open_camera_source
    from lynx.net.client import BackgroundClient
    from lynx.spatial import Pose

    from .discovery import resolve_relay_urls
    from .failover import FailoverClient
    from .holdover import FriendlyHoldover
    from .session import SessionRecorder

    p = plan(profile, urls)
    if p.calibrate:
        try:
            run_calibration(profile, display=not headless)
            p = plan(profile, p.urls)
        except Exception as exc:  # calibration must never keep the HUD from starting
            log.error("calibration failed (%s); starting with the previous / no calibration", exc)
    argv = list(p.argv) + list(extra_argv)
    if headless:
        argv.append("--headless")
    if frames:
        argv += ["--frames", str(frames)]
    args = build_parser().parse_args(argv)
    cfg = config_from_args(args)
    initial = Pose.from_euler(args.x, args.y, args.eye_height, args.heading, args.pitch, args.roll)
    try:
        pose_source = create_pose_source(args.pose, initial)
    except (PoseSourceUnavailableError, ValueError) as exc:
        raise SystemExit(str(exc))
    camera = open_camera_source(args.source, args.width, args.height, args.hfov, args.vfov, seed=args.seed,
                                unknowns=not args.no_unknowns)
    holdover = FriendlyHoldover()

    def rediscover() -> List[str]:
        return resolve_relay_urls(profile.relay_urls, beacon=profile.discovery, squad=profile.squad,
                                  mdns=False) or p.urls

    net = FailoverClient(p.urls, cfg.node_id, cfg.callsign, cfg.team, encoding=cfg.encoding,
                         on_message=holdover.on_message, rediscover=rediscover)
    holdover._link_down_s = net.link_down_s
    recorder = None
    if profile.log_dir:
        recorder = SessionRecorder(Path(profile.log_dir), f"node:{profile.node}",
                                   meta={"node": profile.node, "callsign": profile.callsign, "urls": p.urls,
                                         "calibration": p.calibration})
    drift = None
    cal = load_calibration(profile)
    if cal is not None:
        drift = DriftMonitor.for_calibration(cal, profile.imu_report)
    hook = FieldHook(holdover, drift, recorder, pose_source, net)
    client = HeadsetClient(cfg, camera, pose_source, BackgroundClient(net), hooks=[hook])
    try:
        return run(client, args)
    finally:
        if recorder is not None:
            recorder.close()
