#!/usr/bin/env python3
"""Mass, CG and neck-moment estimate for the TeamLynx Phase 4 helmet build.

Printed-part masses come from the rendered STL volumes (signed-tetrahedron sum) times the
filament density times an effective fill factor for the recommended slicer settings.
COTS masses are datasheet / scale values. Positions are part CGs in the head frame used by
the models (X forward, Y left, Z up, mm), origin at the head+helmet CG, deployed pod.
These positions are the same ones drawn in hardware/openscad/helmet_layout.scad.

Usage: mass_report.py STL_DIR  (writes Markdown to stdout). Standard library only.
"""
from __future__ import annotations

import math
import struct
import sys
from pathlib import Path

G = 9.81

# material: density g/cm3
DENSITY = {"PETG": 1.27, "ASA": 1.07, "PA-CF": 1.15, "TPU": 1.21}

# head-frame CG of each group, mm
POS = {
    "pod": (150, 0, 46),
    "mount": (120, 0, 58),
    "shroud": (105, 0, 55),
    "esp32": (20, 115, 40),
    "rear": (-148, 0, 40),
    "rear_base": (-120, 0, 40),
    "display": (88, -32, -10),
    "display_drv": (50, -80, -5),
    "harness": (-10, 20, 75),
}

# (stl name, material, effective fill, group, qty)
PRINTED = [
    ("pod_body", "ASA", 0.85, "pod", 1),
    ("pod_lid", "PA-CF", 0.95, "pod", 1),
    ("pod_bezel", "ASA", 0.95, "pod", 1),
    ("pod_sled", "PA-CF", 1.00, "pod", 1),
    ("esp32_base", "ASA", 0.85, "esp32", 1),
    ("esp32_lid", "ASA", 0.95, "esp32", 1),
    ("esp32_mount", "PA-CF", 0.90, "esp32", 1),
    ("esp32_jaw", "PA-CF", 1.00, "esp32", 1),
    ("esp32_grommet", "TPU", 1.00, "esp32", 1),
    ("rear_base", "PETG", 0.55, "rear_base", 1),
    ("rear_cassette", "ASA", 0.80, "rear", 1),
    ("rear_rail", "PA-CF", 1.00, "rear", 2),
    ("rear_lid", "ASA", 0.95, "rear", 1),
    ("cable_helmet_saddle", "PETG", 1.00, "harness", 3),
]

# (item, grams, group)
COTS = [
    ("UVC IMX462 board camera + M12 lens (pigtail in harness)", 18, "pod"),
    ("BNO085 breakout (Adafruit 4754)", 3, "pod"),
    ("2x SFH 4715AS on 20 mm stars", 3, "pod"),
    ("LED plate, 2 mm Al 44 x 42.5", 10, "pod"),
    ("Heatsink 40 x 40 x 11 Al", 15, "pod"),
    ("2x 3 mm PC windows 42 x 38", 12, "pod"),
    ("3x PG7 glands, gaskets, diffuser, desiccant", 12, "pod"),
    ("Pod fasteners: 12x M3, 8x M2, inserts", 9, "pod"),
    ("NVG mount, Wilcox G24 (repro mounts 110-150 g)", 162, "mount"),
    ("One-hole shroud (skip if the helmet already has one)", 35, "shroud"),
    ("ESP32-S3-DevKitC-1 + 70x30 carrier + headers + passives", 20, "esp32"),
    ("GX12-6 socket, 3.5 mm panel jack, M3 hardware", 14, "esp32"),
    ("Jetson Orin Nano Super Developer Kit", 176, "rear"),
    ("PDB: perfboard, CH224K trigger, LDD-350L, fuses, MOSFETs", 22, "rear"),
    ("GX12-2 socket, toggle + guard, M3 hardware, inserts", 16, "rear"),
    ("Hook-and-loop, EVA pad, 2x 25 mm strap", 25, "rear_base"),
    ("Micro-OLED engine + eyepiece (inside goggle)", 22, "display"),
    ("HDMI driver board + strap clip", 14, "display_drv"),
    ("Helmet harness: USB x2, IR pair, HDMI FPC, DP-HDMI adapter, sleeving", 95, "harness"),
]


def stl_volume_cm3(path: Path) -> float:
    data = path.read_bytes()
    tris = []
    if data[:5] == b"solid" and b"facet" in data[:400]:
        verts = []
        for line in data.decode(errors="replace").splitlines():
            t = line.split()
            if t and t[0] == "vertex":
                verts.append(tuple(float(v) for v in t[1:4]))
        tris = [verts[i:i + 3] for i in range(0, len(verts), 3)]
    else:
        n = struct.unpack_from("<I", data, 80)[0]
        for i in range(n):
            o = 84 + 50 * i + 12
            v = struct.unpack_from("<9f", data, o)
            tris.append([v[0:3], v[3:6], v[6:9]])
    vol = 0.0
    for a, b, c in tris:
        vol += (a[0] * (b[1] * c[2] - b[2] * c[1])
                - a[1] * (b[0] * c[2] - b[2] * c[0])
                + a[2] * (b[0] * c[1] - b[1] * c[0])) / 6.0
    return abs(vol) / 1000.0


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    stl_dir = Path(sys.argv[1])
    rows = []  # (group, item, grams)
    print("# Helmet mass and balance (generated by hardware/scripts/mass_report.py)\n")
    print("## Printed parts\n")
    print("| Part | Material | Volume cm³ | Fill | Qty | Mass g |")
    print("|---|---|---:|---:|---:|---:|")
    for name, mat, fill, grp, qty in PRINTED:
        p = stl_dir / f"{name}.stl"
        if not p.exists():
            print(f"missing STL: {p}", file=sys.stderr)
            return 1
        v = stl_volume_cm3(p)
        m = v * DENSITY[mat] * fill * qty
        rows.append((grp, f"{name}.stl ({mat})", m))
        print(f"| {name} | {mat} | {v:.1f} | {fill:.2f} | {qty} | {m:.1f} |")
    for item, g, grp in COTS:
        rows.append((grp, item, float(g)))

    print("\n## Head-borne mass by group\n")
    print("| Group | Mass g | CG x, y, z (mm) | Pitch moment m·g·x (N·m) | Roll moment m·g·y (N·m) |")
    print("|---|---:|---|---:|---:|")
    tot = 0.0
    mx = my = mz = 0.0
    for grp in POS:
        m = sum(r[2] for r in rows if r[0] == grp)
        if m == 0:
            continue
        x, y, z = POS[grp]
        tot += m
        mx += m * x
        my += m * y
        mz += m * z
        print(f"| {grp} | {m:.0f} | {x}, {y}, {z} | {m / 1000 * G * x / 1000:+.3f} | {m / 1000 * G * y / 1000:+.3f} |")
    cg = (mx / tot, my / tot, mz / tot)
    print(f"| **total added** | **{tot:.0f}** | **{cg[0]:.1f}, {cg[1]:.1f}, {cg[2]:.1f}** | "
          f"**{tot / 1000 * G * cg[0] / 1000:+.3f}** | **{tot / 1000 * G * cg[1] / 1000:+.3f}** |")

    front = sum(r[2] for r in rows if r[0] in ("pod", "mount", "shroud"))
    fx = sum(r[2] * POS[r[0]][0] for r in rows if r[0] in ("pod", "mount", "shroud"))
    jet_m = sum(r[2] for r in rows if r[0] in ("rear", "rear_base"))
    jet_mx = sum(r[2] * POS[r[0]][0] for r in rows if r[0] in ("rear", "rear_base"))
    print("\n## Sensitivity\n")
    print(f"* Front group (pod + mount + shroud): {front:.0f} g, moment {front / 1000 * G * fx / front / 1000:+.3f} N·m "
          f"at x = {fx / front:.0f} mm.")
    print(f"* Rear group (cassette + base): {jet_m:.0f} g, moment {jet_m / 1000 * G * jet_mx / jet_m / 1000:+.3f} N·m.")
    alt = tot - jet_m
    alt_mx = mx - jet_mx
    print(f"* Jetson body-worn instead (rear group removed): helmet adds {alt:.0f} g with a pitch moment of "
          f"{alt / 1000 * G * alt_mx / alt / 1000:+.3f} N·m nose-down; balancing it needs "
          f"{alt_mx / 140:.0f} g of dead counterweight at x = -140 mm.")
    print(f"* Per 10 mm the pod sits further forward: {sum(r[2] for r in rows if r[0] == 'pod') / 1000 * G * 0.010:+.3f} N·m.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
